#!/bin/bash
set -eu

main() {
  local otp_version="27.0.1"
  local elixir_version="1.17.2"

  for arg in "$@"; do
    if [[ $arg == elixir@* ]]; then
      elixir_version="${arg#elixir@}"
    elif [[ $arg == otp@* ]]; then
      otp_version="${arg#otp@}"
    else
      echo "error: invalid argument $arg" >&2
      exit 1
    fi
  done

  local root_dir="$HOME/.elixir-install"
  local tmp_dir="$root_dir/tmp"
  mkdir -p $tmp_dir

  local otp_release="${otp_version%%.*}"
  local otp_dir="$root_dir/installs/otp/$otp_version"

  local elixir_dir="$root_dir/installs/elixir/$elixir_version-otp-$otp_release"

  install_otp
  printf "checking OTP... "
  export PATH="$otp_dir/bin:$PATH"
  erl -noshell -eval "io:put_chars(erlang:system_info(otp_release)), halt()."
  echo " ok"
  install_elixir
  printf "checking Elixir... "
  $elixir_dir/bin/elixir -e "IO.write System.version()"
  echo " ok"
  export PATH="$elixir_dir/bin:$PATH"
  echo
  echo "Add this to your shell:"
  echo
  echo "    export PATH=\$HOME/.elixir-install/installs/otp/$otp_version/bin:\$PATH"
  echo "    export PATH=\$HOME/.elixir-install/installs/elixir/$elixir_version-otp-$otp_release/bin:\$PATH"
  echo
}

install_otp() {
  local os=`uname -s`
  case $os in
    Darwin) os=darwin ;;
    Linux) os=linux ;;
    MINGW64*) os=windows ;;
    *) echo "error: unsupported OS: $os." && exit 1
  esac

  local arch=`uname -m`
  case $arch in
    x86_64) arch=amd64 ;;
    aarch64) arch=arm64 ;;
    arm64) arch=arm64 ;;
    *) echo "error: unsupported architecture: $arch." && exit 1
  esac

  if [ ! -d $otp_dir/bin ]; then
    if [ "$os" = "windows" ]; then
      ensure_vcredist
      local otp_zip="OTP-$otp_version-windows-amd64.zip"

      if [ ! -f $tmp_dir/$otp_zip ]; then
        local url="https://github.com/elixir-install/otp_builds/releases/download/OTP-$otp_version/$otp_zip"
        echo "downloading $url"
        curl --retry 3 --fail -L -o $tmp_dir/$otp_zip $url
      fi

      echo "unpacking $otp_zip to $otp_dir..."
      mkdir -p "$otp_dir"
      unzip -q "$tmp_dir/$otp_zip" -d "$otp_dir"
      (cd $otp_dir && ./Install.exe -sasl)
      rm "$tmp_dir/$otp_zip"
    fi

    if [ "$os" = "darwin" ]; then
      local otp_tgz="OTP-${otp_version}-macos-$arch.tar.gz"

      if [ ! -f $tmp_dir/$otp_tgz ]; then
        local url="https://github.com/elixir-install/otp_builds/releases/download/OTP-$otp_version/$otp_tgz"
        echo "downloading $url"
        curl --retry 3 --fail -L -o "$tmp_dir/$otp_tgz" $url
      fi

      echo "unpacking $otp_tgz to $otp_dir..."
      mkdir -p $otp_dir
      tar xzf "$tmp_dir/$otp_tgz" -C $otp_dir
      (cd $otp_dir && ./Install -sasl $PWD)
      rm "$tmp_dir/$otp_tgz"
    fi

    if [ "$os" = "linux" ]; then
      local otp_tgz="OTP-${otp_version}.tar.gz"

      if [ ! -f $tmp_dir/$otp_tgz ]; then
        local url="https://builds.hex.pm/builds/otp/$arch/ubuntu-22.04/$otp_tgz"
        echo "downloading $url"
        curl --retry 3 --fail -L -o "$tmp_dir/$otp_tgz" $url
      fi

      echo "unpacking $otp_tgz to $otp_dir..."
      mkdir -p $otp_dir
      tar xzf "$tmp_dir/$otp_tgz" --strip-components 1 -C $otp_dir
      (cd $otp_dir && ./Install -sasl $PWD)
      rm "$tmp_dir/$otp_tgz"
    fi
  fi
}

ensure_vcredist() {
  if [ -f /c/windows/system32/vcruntime140.dll ]; then
    return
  fi

  url="https://aka.ms/vs/17/release/vc_redist.x64.exe"
  file="vc_redist.x64.exe"

  echo "downloading VC++ Redistributable $url..."
  curl --retry 3 --fail -L -o "$file" "$url"
  echo "installing VC++ Redistributable $url..."
  ./"$file" /quiet /norestart
}

install_elixir() {
  local elixir_zip="elixir-otp-$otp_release.zip"

  if [ ! -d $elixir_dir/bin ]; then
    if [ ! -f "$tmp_dir/$elixir_zip" ]; then
      local url="https://github.com/elixir-lang/elixir/releases/download/v$elixir_version/$elixir_zip"
      echo "downloading $url"
      curl --retry 3 --fail -L -o "$tmp_dir/$elixir_zip" $url
    fi
    echo "unpacking $elixir_zip to $elixir_dir..."
    mkdir -p "$elixir_dir"
    unzip -q "$tmp_dir/$elixir_zip" -d "$elixir_dir"
    rm "$tmp_dir/$elixir_zip"
  fi
}

main $@
